name: Iran-Special Collector

on:
  schedule:
    - cron: '0 */2 * * *' # هر دو ساعت یکبار
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install telethon jdatetime tzdata aiohttp

      - name: Run Collector
        env:
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
        run: python collector.py

      - name: Push to Repo
        run: |
          git config --global user.name "IranCheckBot"
          git config --global user.email "bot@github.com"
          git add sub.txt sub_raw.txt
          git commit -m "Update Iran-Working Configs: $(date)" || echo "No changes"
          git push
