name: Iran-Special Collector

on:
  schedule:
    - cron: '0 */2 * * *' # اجرای خودکار هر ۲ ساعت
  workflow_dispatch:      # امکان اجرای دستی

permissions:
  contents: write         # اجازه حیاتی برای آپلود فایل‌ها

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # دریافت کامل تاریخچه برای جلوگیری از تداخل

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install telethon jdatetime tzdata aiohttp

      - name: Run Collector
        env:
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
        run: python collector.py

      - name: Push to Repo
        run: |
          git config --global user.name "IranCheckBot"
          git config --global user.email "bot@github.com"
          
          # ۱. اضافه کردن فایل‌های تغییر یافته
          git add sub.txt sub_raw.txt
          
          # ۲. ثبت تغییرات در صورتی که فایلی واقعا عوض شده باشد
          git diff --staged --quiet || git commit -m "Update Iran-Working Configs: $(date)"
          
          # ۳. همگام‌سازی با سرور (حل مشکل Rejected)
          git pull origin main --rebase
          
          # ۴. آپلود نهایی
          git push origin main
