name: V2Ray Collector Professional

on:
  schedule:
    - cron: '0 */1 * * *' # اجرا در هر ساعت
  workflow_dispatch: # امکان اجرای دستی

permissions:
  contents: write # اجازه نوشتن در مخزن برای رفع خطای 403

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install telethon python-socks[asyncio] jdatetime

      - name: Run collector
        env:
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
        run: python collector.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sub.txt
          # فقط اگر تغییری وجود داشت کامیت انجام شود
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Configs: $(date)" && git push origin main)
