name: V2Ray Collector

on:
  schedule:
    - cron: '*/10 * * * *' # اجرای خودکار هر 10 دقیقه
  workflow_dispatch: # دکمه اجرای دستی

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # برای جلوگیری از تداخل در push

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install telethon python-socks[asyncio]

    - name: Run collector script
      env:
        SESSION_STRING: ${{ secrets.SESSION_STRING }}
        API_HASH: "6f3350e049ef37676b729241f5bc8c5e"
      run: python collector.py

    - name: Commit and Push
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
        # اول تغییرات احتمالی از سمت سرور را می‌گیریم
        git pull origin main --rebase
        
        # حالا فایل جدید را اضافه و کامیت می‌کنیم
        git add sub.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update configs [$(date)]" && git push)
