name: V2Ray Collector

on:
  schedule:
    - cron: '*/10 * * * *' # اجرای خودکار هر 10 دقیقه
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install telethon python-socks[asyncio]

    - name: Run Collector
      env:
        SESSION_STRING: ${{ secrets.SESSION_STRING }}
      run: python collector.py

    - name: Update Repo
      run: |
        git config --global user.name "Bot-Collector"
        git config --global user.email "bot@github.com"
        git add sub.txt
        git commit -m "Update configs [$(date)]" || exit 0
        git push
