name: V2Ray Collector

on:
  repository_dispatch:
    types: [run_update]
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # برای جلوگیری از تداخل در push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install telethon python-socks[asyncio]

      - name: Run collector script
        env:
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          API_HASH: "6f3350e049ef37676b729241f5bc8c5e"
        run: python collector.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # اجبار گیت به هماهنگی با سرور بدون درگیری
          git fetch origin main
          git reset --soft origin/main
          # اضافه کردن فایل و آپلود
          git add sub.txt
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update configs [$(date)]"
            git push origin main --force
          else
            echo "No changes to commit"
          fi
